\documentclass[aspectratio=169]{beamer}
\usepackage{multirow}
%\usecolortheme{beaver}
%\usecolortheme[RGB={129,3,3}]{structure}
\usetheme{CambridgeUS}
\usecolortheme{seahorse}

% Standard header (will need to change date!)
\title[GEOG 5680 Summer '20]{GEOG 5680\\Introduction to R}
\subtitle[Intro]{09: Probabilities and Inference tests}
\author[S. Brewer]{Simon Brewer}
\institute[Univ. Utah]{
  Geography Department\\
  University of Utah\\
  Salt Lake City, Utah 84112\\[1ex]
  \texttt{simon.brewer@geog.utah.edu}
}
\date[May 04, 2020]{May 04, 2020}

\begin{document}
<<setup, include=FALSE>>=
#opts_chunk$set(size = 'footnotesize')
opts_chunk$set(size = 'scriptsize')
@

%--- the titlepage frame -------------------------%
\begin{frame}
  \titlepage
\end{frame}

% %--- Slide ----------------%
% \begin{frame}{Outline}
% \begin{itemize}
%   \item Probability (in R)
%   \item Statistical distributions
%   \item Statistical inference
%   \item $t$-test example
%   \item ANOVA and other standard tests
% \end{itemize}
% \end{frame}
% 
\section{Probability}
%-----frame-----%
\begin{frame}{Probability}
What is this thing called probability?
\begin{itemize}
  \item Mathematical description of uncertainty
  \item Tightly linked to statistics for inference
  \begin{itemize}
    \item Model of population from samples
  \end{itemize}
  \item Several functions in R for estimating probability
  \item Also found as part of the inference in test in other functions (e.g. ANOVA, linear models, etc)
\end{itemize}
\end{frame}

%-----frame-----%
\begin{frame}{Probability}
What is this thing called probability?
\begin{itemize}
  \item Probability shows what \emph{outcomes} might occur given a \emph{model}
  \begin{itemize}
    \item Given the animal, what are the footprints?
  \end{itemize}
  \item<2-> Statistics show what \emph{models} might result in a given \emph{outcome}
  \begin{itemize}
    \item Given the footprints, what is the animal?
  \end{itemize}
\end{itemize}
\end{frame}

% %-----frame-----%
% \begin{frame}{Probability}
% Some vocabulary
% \begin{itemize}
%   \item Outcome
%   \begin{itemize}
%     \item Result of an experiment
%   \end{itemize}
%   \item Sample space
%   \begin{itemize}
%     \item All possible outcomes of an experiment
%   \end{itemize}
%   \item Random variable
%   \begin{itemize}
%     \item Translation of sample space into simpler numerical value
%     \item E.g. How many heads in 10 coin tosses
%     \item Sample space ($\Omega$) has $2^{10}$ entries
%     \item Random variable ($X$) has just 11: $\{ 0,1,2,3,4,5,6,7,8,9,10 \}$
%   \end{itemize}
% \end{itemize}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}{Probability}
% Some vocabulary
% \begin{itemize}
%   \item Probability
%   \begin{itemize}
%     \item Chance of a given outcome ($x_i$) in random variable occuring
%     \item $0 \le p(x_i) \le 1$
%   \end{itemize}
%   \item Probability distribution 
%   \begin{itemize}
%     \item List of probabilities for all possible outcomes defined in random variable
%     \item $\sum p(x_i) = 1$
%   \end{itemize}
% \end{itemize}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}{Probability mass function}
% \begin{columns}
%   \begin{column}{0.5\textwidth}
%   \begin{itemize}
%     \item Probability mass function
%     \item Used with discrete variables (binary, counts, etc)
%     \item Value given is probability for that outcome
%     \item E.g. $p(2)=$ \Sexpr{dpois(2,4)}
%   \end{itemize}
%   \end{column}
%   \begin{column}{0.5\textwidth}
% <<echo=FALSE>>=
% set.seed(8888)
% #x1 = rpois(100, 4)
% x1 = seq(0,12)
% d1 = dpois(x1, 4)
% barplot(d1, names.arg = x1, main="Number of trees (prob. mass)")
% abline(h=dpois(2,4), lty=2)
% @
%   \end{column}
% \end{columns}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}{Probability density function}
% \begin{columns}
%   \begin{column}{0.5\textwidth}
%   \begin{itemize}
%     \item Probability density function
%     \item Used with continuous variables
%     \item Value given is \emph{density} of probability, not probability
%   \end{itemize}
%   \end{column}
%   \begin{column}{0.5\textwidth}
% <<echo=FALSE>>=
% x2 = rnorm(100, 160,15)
% qq = seq(0,250,1)
% dd = dnorm(qq,160,15)
% plot(qq, dd, main="Student height (prob. density)", type='l', lwd=2, 
%      xlab="cm", ylab="D", xlim=c(100,220))
% @
%   \end{column}
% \end{columns}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}{Probability density function}
% \begin{columns}
%   \begin{column}{0.5\textwidth}
%   \begin{itemize}
%     \item Value given is \emph{density} of probability, not probability
%     \item Use integrals to estimate the probability of being less than (or greater than) a given value
%     \item E.g. $p(<155)=$ \Sexpr{round(pnorm(155, 160, 15, lower.tail=TRUE),4)}
%   \end{itemize}
%   \end{column}
%   \begin{column}{0.5\textwidth}
% <<echo=FALSE>>=
% plot(qq, dd, main="Student height (prob. density)", type='l', lwd=2, 
%      xlab="cm", ylab="D", xlim=c(100,220))
% xvals <- seq(50,155,length=100)
% dvals <- dnorm(xvals,160,15)
% polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
% text(120,0.02,
%      paste("p(<155)=",round(pnorm(155, 160, 15, lower.tail=TRUE),4)))
% @
%   \end{column}
% \end{columns}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}{Probability density function}
% \begin{columns}
%   \begin{column}{0.5\textwidth}
%   \begin{itemize}
%     \item Value given is \emph{density} of probability, not probability
%     \item Use integrals to estimate the probability of being less than (or greater than) a given value
%     \item E.g. $p(>180)=$ \Sexpr{round(pnorm(180, 160, 15, lower.tail=FALSE),4)}
%   \end{itemize}
%   \end{column}
%   \begin{column}{0.5\textwidth}
% <<echo=FALSE>>=
% plot(qq, dd, main="Student height (prob. density)", type='l', lwd=2, 
%      xlab="cm", ylab="D", xlim=c(100,220))
% xvals <- seq(180,250,length=100)
% dvals <- dnorm(xvals,160,15)
% polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
% text(120,0.02,
%      paste("p(>180)=",round(pnorm(180, 160, 15, lower.tail=FALSE),4)))
% @
%   \end{column}
% \end{columns}
% \end{frame}
% 
\section{Distributions in R}
%--- Slide ----------------%
\begin{frame}{Distributions in R}
\begin{itemize}
  \item R comes as standard with approx. 20 well-known probability distribution functions
  \item Including normal, uniform, binomial, log-normal, beta, gamma, $t$, $F$, $\chi^2$ etc
  \item Add-on packages include approx 100+ extra distributions
  \item Most distribution come with four functions:
  \begin{itemize}
    \item \texttt{d*} --- density functions (e.g. \texttt{dnorm()})
    \item \texttt{p*} --- probability distribution functions (e.g. \texttt{pnorm()})
    \item \texttt{q*} --- quantile functions (e.g. \texttt{qnorm()})
    \item \texttt{r*} --- random number generation (e.g. \texttt{rnorm()})
  \end{itemize}
  \item Look at examples with Poisson (discrete, count) and normal (continuous)
\end{itemize}
\end{frame}

\subsection{Poisson distribution}
%-----frame-----%
\begin{frame}[fragile]{Poisson distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Count data ($\lambda$ = mean count)
    \item \texttt{d*}: density function, gives the height of the density curve for a given value
    \item E.g what is the probability of getting 6 trees in a quadrat?
  \end{itemize}
<<>>=
dpois(6,lambda=4)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
set.seed(8888)
#x1 = rpois(100, 4)
x1 = seq(0,12)
d1 = dpois(x1, 4)
df.bar <- barplot(d1, names.arg = x1, main="Number of trees (prob. mass)") 
arrows(df.bar[7],0,df.bar[7],dpois(6,4), lwd=2, col=2)
abline(h=dpois(6,4), lwd=2, lty=2, col=2)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Poisson distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Count data ($\lambda$ = mean count)
    \item \texttt{p*}: probability dist. function, gives the integral above or below that value
    \item E.g what is the probability of getting $\le 6$ trees in a quadrat?
  \end{itemize}
<<>>=
ppois(6,lambda=4, 
      lower.tail = TRUE)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
#par(mfrow=c(2,1))
df.bar <- barplot(d1, names.arg = x1, main="Number of trees (prob. mass)", col=c(rep(2,7),rep(1,6)))
# p1 <- ppois(q=seq(0,12,by=1), 4)
# #df.bar <- barplot(p1, names.arg = x1, main="Number of trees (cumul. prob. mass)", col=c(rep(2,7),rep(1,6)))
# plot(x1, p1, main="Number of trees (cumul. prob. mass)", type='s')
# abline(v=6, lty=2)
# abline(h=ppois(6,lambda=4, 
#       lower.tail = TRUE), lty=2)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Poisson distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Count data ($\lambda$ = mean count)
    \item \texttt{q*}: quantile function, gives the values of $X$ corresponding to a percentile probability
    \item E.g how many trees do we expect at the 10 percentile of the distribution?
  \end{itemize}
<<>>=
qpois(0.1,lambda=4)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
# par(mfrow=c(2,1))
df.bar <- barplot(d1, names.arg = x1, main="Number of trees (prob. mass)", col=c(rep(2,3),rep(1,10)))
# s1 <- seq(0,0.95,by=0.05)
# q1 <- qpois(s1, 4)
# plot(s1, q1, main="Number of trees (cumul. prob. mass)", type='s')
# abline(v=0.1, lty=2)
# abline(h=2, lty=2)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Poisson distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Count data ($\lambda$ = mean count)
    \item \texttt{q*}: quantile function, gives the values of $X$ corresponding to a percentile probability
    \item E.g what is the 95\% CI on the number of trees we expect?
  \end{itemize}
<<>>=
qpois(c(0.025,0.975),lambda=4)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
# par(mfrow=c(2,1))
df.bar <- barplot(d1, names.arg = x1, main="Number of trees (prob. mass)", col=c(rep(1,1),rep(2,8),rep(1,4)))
# s1 <- seq(0,0.95,by=0.05)
# q1 <- qpois(s1, 4)
# plot(s1, q1, main="Number of trees (cumul. prob. mass)", type='s')
# abline(v=0.1, lty=2)
# abline(h=2, lty=2)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Poisson distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Count data ($\lambda$ = mean count)
    \item \texttt{r*}: random function, generates random samples from the distribution
    \item E.g how many trees might be found in the next four plots?
  \end{itemize}
<<>>=
rpois(4,lambda=4)
rpois(4,lambda=4)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
hist(rpois(1000,4), main="Number of trees (1000 random samples)",
     breaks=seq(-0.5,15.5), xlim=c(0,12), xlab="Ntrees", freq=F)
lines(x1, d1, type='h', lwd=3, col=2)
legend("topright", fill=c("white","red"), legend=c("rpois","dpois"))
@
  \end{column}
\end{columns}
\end{frame}

\subsection{Normal distribution}
%-----frame-----%
\begin{frame}[fragile]{Normal distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Continuous data ($\mu$ = mean, $\sigma$ = std.dev.)
    \item \texttt{d*}: density function, gives the height of the density curve for a given value
    \item E.g what is the probability density for a height of 150cm?
  \end{itemize}
<<>>=
dnorm(150,mean = 160, sd=15)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
x2 = rnorm(100, 160,15)
qq = seq(0,250,1)
dd = dnorm(qq,160,15)
plot(qq, dd, main="Student height (prob. density)", type='l', lwd=2, 
     xlab="cm", ylab="D", xlim=c(100,220))
arrows(150,0,150, dnorm(150,mean = 160, sd=15), lwd=2, col=2)
abline(h=dnorm(150,mean = 160, sd=15), lwd=2, lty=2, col=2)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Normal distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Continuous data ($\mu$ = mean, $\sigma$ = std.dev.)
    \item \texttt{p*}: probability dist. function, gives the integral above or below that value
    \item E.g what is the probability of a student being smaller than 140cm?
  \end{itemize}
<<>>=
pnorm(140, 160, 15, 
      lower.tail = TRUE)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
#par(mfrow=c(2,1))
plot(qq, dd, main="Student height (prob. density)", type='l', lwd=2, 
     xlab="cm", ylab="D", xlim=c(100,220))
xvals <- seq(80,140,length=100)
dvals <- dnorm(xvals,160,15)
polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
text(120,0.02,
     paste("p(<140)=",round(pnorm(140, 160, 15, lower.tail=FALSE),4)))
# p1 = pnorm(qq, 160, 15, 
#       lower.tail = TRUE)
# plot(qq, p1, main="Number of trees (cumul. prob. mass)", type='s',
#      xlim=c(100,220))
# abline(v=6, lty=2)
# abline(h=ppois(6,lambda=4, 
#       lower.tail = TRUE), lty=2)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Normal distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Continuous data ($\mu$ = mean, $\sigma$ = std.dev.)
    \item \texttt{q*}: quantile function, gives the values of $X$ corresponding to a percentile probability
    \item E.g what cutoff in height gives me the top $5\%$ of students?
  \end{itemize}
<<>>=
qnorm(0.95, 160, 15)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
cutoff = qnorm(0.95, 160, 15)
plot(qq, dd, main="Student height (prob. density)", type='l', lwd=2, 
     xlab="cm", ylab="D", xlim=c(100,220))
xvals <- seq(cutoff,250,length=100)
dvals <- dnorm(xvals,160,15)
polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="red")
text(120,0.02,
     paste("p(<140)=",round(pnorm(140, 160, 15, lower.tail=FALSE),4)))
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Normal distribution}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Continuous data ($\mu$ = mean, $\sigma$ = std.dev.)
    \item \texttt{r*}: random function, generates samples from the distribution
    \item E.g heights of 3 random students?
  \end{itemize}
<<>>=
rnorm(3, 160, 15)
rnorm(3, 160, 15)
@
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
hist(rnorm(1000, 160, 15), main="Student heights (1000 random samples)",
     freq=FALSE, xlab="cm")
lines(qq, dd, lwd=2, col=2)
legend("topright", fill=c("white","red"), legend=c("rnorm","dnorm"))
@
  \end{column}
\end{columns}
\end{frame}

\section{Statistical Inference}
%-----frame-----%
\begin{frame}{Statistical Inference}
Statistical Inference and hypothesis testing
\begin{itemize}
  \item Test some assumptions about a population of interest, using data drawn or sampled from that population
  \item Compared to descriptive statistics, inference gives significance of a statistical observation
  \item Examples
  \begin{itemize}
    \item Do two sets of observations have the same characteristics (mean, variance)?
    \item Are two variables correlated among a set of observations?
    \item Are observations distributed equally or not?
  \end{itemize}
\end{itemize}
\end{frame}

% %-----frame-----%
% \begin{frame}{Statistical Inference}
% \begin{itemize}
%   \item In general we wish to compare a statistic (e.g. mean) of a sample to a theoretical value or to another sample to look for differences
%   \item We use a \textit{test}-statistic to measure the difference, then compare this to a reference distribution of these statistics
%   \item The reference distribution tells us how much difference might be expected due to sample variation
%   \item If the observed statistic is much different from the expected range of values of the distribution, (i.e. does it fall in the tail-ends of the distribution) we might infer that the differences have not arisen by chance.
% \end{itemize}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}{Statistical Inference}
% \begin{itemize}
%   \item Choices to be made
%   \begin{itemize}
%     \item Which statistic (from descriptive statistic)?
%     \item Which reference distribution (of all possible values)?
%     \begin{itemize}
%       \item Theoretical
%       \item Empirical
%     \end{itemize}
%     \item What degree of certainty?
%     \begin{itemize}
%       \item Usually $<5\%$ of distribution?
%     \end{itemize}
%   \end{itemize}
% \end{itemize}
% \end{frame}
% 
\subsection{Student's $t$-test}
%-----frame-----%
\begin{frame}{Student's $t$-test}
\begin{columns}
  \begin{column}{0.75\textwidth}
  \begin{itemize}
    \item A $t$-test is used to compare an observed sample mean ($\mu_1$) to a hypothesized value ($\mu_{0}$) (one sample $t$-test)
    \item Or to compare two sample means (two sample $t$-test)
    %\item Answers the question: Is the difference in values ($\mu_1 - \mu_2$) large or small?
  \end{itemize}
  \begin{equation}
  t = \frac{\mu_1 - \mu_2}{s_{\mu_1-\mu2}}
  \end{equation}
  \begin{itemize}
    \item One-tailed ($\mu_1 < \mu_2$ or $\mu_1 > \mu_2$)
    \item Two-tailed ($\mu_1 \ne \mu_2$)
  \end{itemize}
  \end{column}
  \begin{column}{0.25\textwidth}
  \begin{center}
    	\includegraphics[width=0.95\textwidth]{./images/guinnessbeer.png}
  \end{center}
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
<<echo=FALSE>>=
set.seed(6666)
apop1 = rnorm(50, mean=180, sd=10)
apop2 = rnorm(50, mean=180, sd=10)
@
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{center}
    	\includegraphics[width=0.55\textwidth]{./images/Aragorn.png}
  \end{center}
  \begin{itemize}
    \item Two samples ($n=50$) of actors who auditioned for the role of Aragorn in Lord of the Rings in two different locations
    \item Is there a difference in heights?
  \end{itemize}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
# mybreaks=seq(140,210,by=5)
# par(mfrow=c(2,1))
# hist(apop1, breaks=mybreaks, main="Actors heights (location 1)")
# hist(apop2, breaks=mybreaks, main="Actors heights (location 2)")
library(ggplot2)
location = c(rep("Loc1",50), rep("Loc2",50))
out.df = data.frame(location, heights=c(apop1,apop2))
x = ggplot(out.df, aes(x=heights, fill=location)) + 
  geom_histogram(binwidth=5, alpha=0.5, position="identity")
x = x + ggtitle("Histogram of actors heights") + theme(legend.position = "bottom")
print(x)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Is there a difference in mean height?
    \item Loc. 1 mean = \Sexpr{round(mean(apop1),2)}
    \item Loc. 2 mean = \Sexpr{round(mean(apop2),2)}
    \item Difference = \Sexpr{round(mean(apop1)-mean(apop2),2)}
    \item $t$-statistic = \Sexpr{round(t.test(apop1,apop2)$statistic,4)}
  \end{itemize}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
# mybreaks=seq(140,210,by=5)
# par(mfrow=c(2,1))
# hist(apop1, breaks=mybreaks, main="Actors heights (location 1)")
# hist(apop2, breaks=mybreaks, main="Actors heights (location 2)")
x = x + geom_vline(xintercept=c(mean(apop1),mean(apop2)))
print(x)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Compare $t$-statistic to $t$-distribution
    \item Represents the range of $t$-statistics expected through normal random variation
    \item If observed $t$ has a low probability (i.e. in one of the tails), it is less likely to have occured by chance ($p$-value)
    %\item The $p$-value represents the probability that this value (or larger) could have occurred by chance
    %\item Calculate as integral of distribution $<$ or $>$ this value
  \end{itemize}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
qq=seq(-4,4,by=0.1)
plot(qq,dt(qq,96.79), type='l', xlab="t", ylab="D", main="t-distribution, df=96.79")
@
  \end{column}
\end{columns}
\end{frame}

% %-----frame-----%
% \begin{frame}[fragile]{Student's $t$-test}
% \begin{columns}
%   \begin{column}{0.5\textwidth}
%   \begin{itemize}
%     \item One-tail (greater than) test:
%     \item The $p$-value represents the probability that this value (or more) could have occurred by chance
%     \begin{itemize}
%       \item $p$-value is integral of curve $>$ $t$-statistic
%       \item $p$-value = \Sexpr{round(t.test(apop1,apop2, alternative="greater")$p.value,4)}
%     \end{itemize}
%   \end{itemize}
%   \end{column}
%   \begin{column}{0.5\textwidth}
% <<echo=FALSE>>=
% xt <- t.test(apop1,apop2)$statistic
% plot(qq,dt(qq,96.79), type='l', xlab="t", ylab="D", main="t-distribution, df=96.79")
% xvals <- seq(xt,4,length=100)
% dvals <- dt(xvals,96.79)
% polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
% @
%   \end{column}
% \end{columns}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}[fragile]{Student's $t$-test}
% $t$-test in R using the \texttt{t.test()} function:
% <<echo=TRUE>>=
% t.test(apop1, apop2, alternative = "greater")
% @
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}[fragile]{Student's $t$-test}
% \begin{columns}
%   \begin{column}{0.5\textwidth}
%   \begin{itemize}
%     \item One-tail (lesser than) test:
%     \item The $p$-value represents the probability that this value (or less) could have occurred by chance
%     \item One-tail test:
%     \begin{itemize}
%       \item $p$-value is integral of curve $<$ $t$-statistic
%       \item $p$-value = \Sexpr{round(t.test(apop1,apop2, alternative="less")$p.value,4)}
%     \end{itemize}
%   \end{itemize}
%   \end{column}
%   \begin{column}{0.5\textwidth}
% <<echo=FALSE>>=
% xt <- t.test(apop1,apop2)$statistic
% plot(qq,dt(qq,96.79), type='l', xlab="t", ylab="D", main="t-distribution, df=96.79")
% xvals <- seq(-4,xt,length=100)
% dvals <- dt(xvals,96.79)
% polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
% @
%   \end{column}
% \end{columns}
% \end{frame}
% 
% %-----frame-----%
% \begin{frame}[fragile]{Student's $t$-test}
% $t$-test in R using the \texttt{t.test()} function:
% <<echo=TRUE>>=
% t.test(apop1, apop2, alternative = "less")
% @
% \end{frame}
% 
%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item Two-tail test:
    \item The $p$-value represents the probability that this \emph{difference} (positive or negative) could have occurred by chance
    \begin{itemize}
      \item $p$-value is integral of curve $< -|t|$ plus integral of curve $> |t|$
      \item $p$-value = \Sexpr{round(t.test(apop1,apop2, alternative="two.sided")$p.value,4)}
    \end{itemize}
  \end{itemize}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
xt <- t.test(apop1,apop2)$statistic
plot(qq,dt(qq,96.79), type='l', xlab="t", ylab="D", main="t-distribution, df=96.79")
xvals <- seq(-4,-1*abs(xt),length=100)
dvals <- dt(xvals,96.79)
polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
xvals <- seq(abs(xt),4,length=100)
dvals <- dt(xvals,96.79)
polygon(c(xvals,rev(xvals)),c(rep(0,100),rev(dvals)),col="lightgray")
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
$t$-test in R using the \texttt{t.test()} function:
<<echo=TRUE>>=
t.test(apop1, apop2, alternative = "two.sided")
@
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
<<echo=FALSE>>=
gimli = rnorm(50, mean=152, sd=15)
aragorn = rnorm(50, mean=180, sd=10)
roles = c(rep("Aragorn",50), rep("Gimli",50))
heights = c(aragorn, gimli)
mybrks=seq(50,250,by=5)
@
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item If we also had 50 actors who auditioned for Gimli + 50 who auditioned for Aragorn
    \item Difference = \Sexpr{round(mean(aragorn)-mean(gimli),2)}
    \item $t$-statistic = \Sexpr{round(t.test(aragorn,gimli)$statistic,4)}
  \end{itemize}
  \begin{center}
      \includegraphics[width=0.55\textwidth]{./images/Gimli.jpg}
  \end{center}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
# hist(aragorn, density=10, xlim=range(c(aragorn,gimli)), 
#      main="Sample of actors heights", breaks=mybrks)
# hist(gimli, density=10, col=2, angle=135, add=TRUE, breaks=mybrks)
# legend('topleft', fill=c(1,2), legend=c("Aragorn", "Gimli"))
out.df = data.frame(roles, heights)
x = ggplot(out.df, aes(x=heights, fill=roles)) + 
  geom_histogram(binwidth=5, alpha=0.5, position="identity")
x = x + ggtitle("Histogram of actors heights") + theme(legend.position = "bottom")
x = x + geom_vline(xintercept=c(mean(aragorn),mean(gimli)))
print(x)
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item The $p$-value represents the probability that this value (or larger) could have occurred by chance
    \item Two-tail test:
    \begin{itemize}
      \item $p$-value is integral of curve $< -|t|$ plus integral of curve $> |t|$
      \item $p$-value = \Sexpr{t.test(aragorn,gimli, alternative="two.sided")$p.value}
    \end{itemize}
  \end{itemize}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
qq = seq(-20,20,by=0.05)
xt <- t.test(aragorn,gimli)$statistic
plot(qq,dt(qq,86.45), type='l', xlab="t", ylab="D", main="t-distribution, df=86.45")
polygon(c(xt,20,20,xt),c(0,0,1,1),col="lightgray")
polygon(c(-20,-1*xt,-1*xt,-20),c(0,0,1,1),col="lightgray")
@
  \end{column}
\end{columns}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
$t$-test in R using the \texttt{t.test()} function:
<<echo=TRUE>>=
t.test(aragorn, gimli, alternative = "two.sided")
@
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{Student's $t$-test}
$t$-test in R using the \texttt{t.test()} function (one-sided):
<<echo=TRUE>>=
t.test(aragorn, gimli, alternative = "greater")
@
\end{frame}

\subsection{ANOVA}
%-----frame-----%
\begin{frame}[fragile]{ANOVA}
<<echo=FALSE>>=
legolas = rnorm(50, mean=195, sd=10)
mybrks=seq(50,250,by=5)
@
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{itemize}
    \item What if we have more than two groups?
    \item If we also have 50 actors who auditioned for Legolas
  \end{itemize}
  \begin{center}
      \includegraphics[width=0.55\textwidth]{./images/Legolas.jpg}
  \end{center}
  \end{column}
  \begin{column}{0.5\textwidth}
<<echo=FALSE>>=
# hist(aragorn, density=10, xlim=range(c(aragorn,gimli,legolas)), 
#      main="Sample of actors heights", breaks=mybrks)
# hist(gimli, density=10, col=2, angle=135, add=TRUE, breaks=mybrks)
# hist(legolas, density=10, col=3, angle=180, add=TRUE, breaks=mybrks)
# legend('topleft', fill=c(1,2,3), legend=c("Aragorn", "Gimli","Legolas"))
roles = c(rep("Aragorn",50), rep("Gimli",50), rep("Legolas",50))
heights = c(aragorn, gimli, legolas)
out.df = data.frame(roles, heights)
x = ggplot(out.df, aes(x=heights, fill=roles)) + 
  geom_histogram(binwidth=5, alpha=0.5, position="identity")
x = x + ggtitle("Histogram of actors heights") + theme(legend.position = "bottom")
print(x)
@
  \end{column}
\end{columns}
\end{frame}

% %--- Slide ----------------%
% \begin{frame}{ANOVA}
% Analysis of variance --- ANOVA
% \begin{itemize}
%   \item ANOVA can be used to compare the means of two or more groups 
% 	\item Extension of the $t$-test for differences of the means of two groups, but different approach
% 	\item Uses the variances of the observations to compare means
% 	\item Has additional uses in regression analysis
% 	\item $H_0$ --- there is no difference between the $n$ groups
% 	\item $H_a$ --- at least one of the $n$ groups has a different mean
% \end{itemize}
% \end{frame}
% 
% %--- Slide ----------------%
% % \begin{frame}{ANOVA}
% % 	\begin{center}
% % 		\includegraphics[width=0.7\textwidth]{./images/aov.png}
% % 	\end{center}
% % \end{frame}
% 
% %--- Slide ----------------%
% \begin{frame}{ANOVA}
% Calculation of ANOVA by variance decomposition
% \begin{itemize}
% 	\item Samples have a total variance $\sigma^2$
% 	\item Knowing group membership, the contribution of any observation $x_{ij}$ to this variance can be split into two parts
% \end{itemize}
% \begin{equation}
% 	(x_{ij} - \bar{x}) = (\bar{x_i} - \bar{x}) + (x_{ij} - \bar{x_i})
% \end{equation}
% \begin{itemize}
% 	\item Where $x_{ij}$ is the value for observation $j$; $\bar{x_i}$ is the mean of a given group $i$; $\bar{x}$ is the overall mean
% \end{itemize}
% \end{frame}
% 
% %--- Slide ----------------%
% \begin{frame}{ANOVA}
% Decomposition of variance for a dataset with three groups
% 	\begin{center}
% 		\includegraphics[width=0.6\textwidth]{./images/sourcesofvariance}
% 	\end{center}
% \end{frame}
% 
% %--- Slide ----------------%
% \begin{frame}{ANOVA}
% We now square and sum the differences for each observations as follow
% \begin{equation}
% 	\sum_{i=1}^{t} \sum_{j=1}^{n} (x_{ij} - \bar{x})^2 = 
% 	n \sum_{i=1}^{t} (\bar{x_i} - \bar{x})^2 + 
% 	\sum_{i=1}^{t} \sum_{j=1}^{n} (x_{ij} - \bar{x_i})^2
% \end{equation}
% \emph{Total} variation or \emph{sum of squares} may be split into \emph{between} and
% \emph{error} components. 
% Frequently written as:
% \begin{equation}
% 	TSS = BSS + ESS
% \end{equation}
% \end{frame}

%--- Slide ----------------%
\begin{frame}{ANOVA}
The $F$-statistic is used to test for significance in the split of variance:
\begin{equation}
		F = \frac{BSS/(t-1)}{ESS/(n-t-1)} 
\end{equation}
\begin{itemize}
	\item Ratio of how much of the variance is between the groups to how much is within the groups
	\item Compare to an $F$-distribution, using degrees of freedom based on the number of groups ($t$) and the number of observations ($n$)
\end{itemize}
\end{frame}

%-----frame-----%
\begin{frame}[fragile]{ANOVA}
  \begin{itemize}
    \item We can use the R function \texttt{aov()} to calculate ANOVA for the three groups. Note this uses the model syntax ($\sim$)
  \end{itemize}
<<echo=TRUE>>=
roles = c(rep("Aragorn",50), rep("Gimli",50), rep("Legolas",50))
heights = c(aragorn, gimli, legolas)
summary(aov(heights ~ roles))
@
\end{frame}

\section{Other inference tests}
%-----frame-----%
\begin{frame}{Other inference tests}
\begin{itemize}
  \item $F$-test: test if difference in ratio of variance of two samples
  \begin{itemize}
    \item \texttt{var.test()}
  \end{itemize}
  \item Wilcoxon rank sum test: Non-parametric test for the equality of medians 
  \begin{itemize}
    \item \texttt{wilcox.test()}
  \end{itemize}
  \item Correlation tests: tests of \emph{covariation}
  \begin{itemize}
    \item \texttt{cor.test()}
    \item Pearson's vs. Spearman's
  \end{itemize}
  \item Chi-squared ($\chi^2$) tests: tests of \emph{distribution} and \emph{association}
  \begin{itemize}
    \item \texttt{chisq.test()}
  \end{itemize}
\end{itemize}
\end{frame}

% %--- Slide ----------------%
% \begin{frame}{Next Class}
% \begin{itemize}
%   \item 0302: Extending R with addon packages
%   \item Lab: Inference tests in R
% \end{itemize}
% \end{frame}
% 
\end{document}