---
title: |
  | GEOG 5680 6680
  | Introduction to R
author: 
  - name: "Simon Brewer"
    email: simon.brewer@ess.utah.edu
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    embed-resources: true
    output-file: "index"
editor: source
---

# Introduction

Spatial data science is a fast-growing discipline, with wide-ranging applications, including human health, economics, water resources, energy and food security, infrastructure, natural hazards, and biodiversity. This class is designed to provide an introduction to the methods used to work with these data, including data acquisition and manipulation, building predictive model pipelines and spatial simulation approaches. Students taking this class will learn both the theory and practice of using these methods through a combination of lecture and hand-on computer work. Over the course of the semester, students will develop their own spatial data analytical projects, which will include the design and implementation of the project as well as the communication of results. 

# Modules

- Module 00: 
    - [Installation instructions][m00]
    - [Using CSBS services][m00b]
- Module 01: 
    - [Introduction to R][m01]
- Module 02: 
    - [Basic data manipulation][m02]
- Module 03: 
    - [Basic plotting][m03]
- Module 04: 
    - [R Functions][m04]
- Module 05: 
    - [Control statements][m05]
- Module 06: 
    - [Report generation][m06]
- Module 07: 
    - [Making figures with ggplot2][m07]
- Module 08: 
    - [Data manipulation with dplyr][m08]
- Module 09: 
    - [Probability distributions and inference tests][m09]
- Module 10: 
    - [Statistical models][m10]
- Module 11: 
    - [Working with large data][m11]
- Module 12: 
    - [Spatial data in R][m12]
- Module 13: 
    - [R and Github][m13]
- Module 14: 
    - [Shiny webapps][m12]
- Module 15: 
    - Choose **one** of:
    - [Publication ready plots with **ggpubr**][m15a]
    - [Generalized linear models][m15b]
    - [Better maps with **tmap**][m15c]
    - [Mixed-effects models][m15d]

# Data

# Links


[m00]: https://simonbrewer.github.io/geog5680/GEOG_5680_00.html
[m00b]: https://simonbrewer.github.io/geog5680/GEOG_5680_00b.html
[m01]: https://simonbrewer.github.io/geog5680/GEOG_5680_01.html
[m02]: https://simonbrewer.github.io/geog5680/GEOG_5680_02.html
[m03]: https://simonbrewer.github.io/geog5680/GEOG_5680_03.html
[m04]: https://simonbrewer.github.io/geog5680/GEOG_5680_04.html
[m05]: https://simonbrewer.github.io/geog5680/GEOG_5680_05.html
[m06]: https://simonbrewer.github.io/geog5680/GEOG_5680_06.html
[m07]: https://simonbrewer.github.io/geog5680/GEOG_5680_07.html
[m08]: https://simonbrewer.github.io/geog5680/GEOG_5680_08.html
[m09]: https://simonbrewer.github.io/geog5680/GEOG_5680_09.html
[m10]: https://simonbrewer.github.io/geog5680/GEOG_5680_10.html
[m11]: https://simonbrewer.github.io/geog5680/GEOG_5680_11.html
[m12]: https://simonbrewer.github.io/geog5680/GEOG_5680_12.html
[m13]: https://simonbrewer.github.io/geog5680/GEOG_5680_13.html
[m14]: https://simonbrewer.github.io/geog5680/GEOG_5680_14.html
[m15a]: https://simonbrewer.github.io/geog5680/GEOG_5680_15a.html
[m15b]: https://simonbrewer.github.io/geog5680/GEOG_5680_15b.html
[m15c]: https://simonbrewer.github.io/geog5680/GEOG_5680_15c.html
[m15d]: https://simonbrewer.github.io/geog5680/GEOG_5680_15d.html
