---
title: "GEOG 5680 6680 Project 2: Market Prices"
author: | 
  | Simon Brewer
  | Geography Department
  | University of Utah
date: "June 09, 2021"
output:
  html_document:
    toc: true
    toc_float: true
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(png)
library(grid)
```

### Introduction

The excel file *Forbes.csv* contains information about 2000 companies, published by Forbes. We are interested in companies profits, both how these are distributed across different types of company and different geographical regions. The file contains the following information:

- `rank`: Forbes ranking
- `name`: Company name
- `country`: Country
- `category`: Company type
- `sales`: annual sales in $M
- `profits`: annual profits in $M
- `assets`: assets in $M
- `marketvalue`: market value

### Analysis

1. Using this file, explore the relationship of profits to the other variables. Which company types generate the highest (and lowest) profits? Which countries generate the most profits? What about sales?

2. Compare the USA and Japan. Which country has the highest rank using Forbes ranking? Which company types are more common in the USA? In Japan?

3. Now build a multiple linear regression model to estimate profits using assets, market value and sales. Use the `summary()` function to find the coefficients and goodness-of-fit of the model. Use the `anova()` function to identify which variable appears to have the greatest effect on profits. Remember to look at the distribution of residuals. 

4. Build two models using the same variables but for Japanese and American companies. Use the `anova()` function to look at which variables are the most important for each region? What differences do you observe?

### Report

You should submit the results of your analysis as an HTML document generated by R Markdown. In addition to the results, this document should contain a brief description of the steps you took, and what the results mean. 

---