---
title: "GEOG 5680 Project 3: Cloud Seeding"
author: "Simon Brewer"
date: "May 14, 2020"
output: pdf_document
---

### Introduction
The excel file *clouds.csv* contains information about a set of cloud seeding experiments. The data were collected in the summer of 1975 from an experiment to investigate the use of massive amounts of silver iodide 100 to 1000 grams per cloud) in cloud seeding to increase rainfall. Our interest is to know whether or not seeding increases the rainfall from a cloud. The file contains the following information:

- seeding: a factor indicating whether seeding action occured (no or yes).
- time: number of days after the first day of the experiment.
- sne: suitability criterion.
- cloudcover: the percentage cloud cover in the experimental area, measured using radar.
- prewetness: the total rainfall in the target area one hour before seeding (in cubic metres times 1e+8).
- echomotion: a factor showing whether the radar echo was moving or stationary.
- rainfall: the amount of rain in cubic metres times 1e+8.

### Analysis
1. Explore the difference in rainfall between seeding and non-seeding experiments by looking at the statistical characteristics (mean, sd, etc) of the experiments and by using visualization. Use a *t*-test to see whether there is a significant difference.

2. Build a multiple linear regression model to model the effects of seeding on rainfall. Include cloudcover, prewetness, echomotion and 'sne' as independent variables. Explore the model using the `summary()` and `anova()` functions. Which variables appear to influence rainfall the most? 

3. As the suitability index (sne) appears to have a relationship with rainfall, build two new models relating this variable to rainfall, one for the seeding experiments, one for the non-seeding experiments. Compare the coefficients for the two models, and produce a figure showing the two models. What does the difference in slope suggest?

### Report
You should submit the results of your analysis as an HTML document generated by R Markdown. In addition to the results, this document should contain a brief description of the steps you took, and what the results mean. 

---